version: "3"
services:

  customer:
    image: customer:1.0-SNAPSHOT
    build: customer/
    depends_on:
      - mysqldb
#    environment:
#      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://customer:8761/mysqldb"}}}}'
    ports:
      - "8081:8081"
    networks:
      - customer-mysql

  mysqldb:
    image: mysql:8
    networks:
      - customer-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root

networks:
  customer-mysql: